services:
  - type: web
    name: super-mercado
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn.conf.py "app:create_app()"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app
      - key: SECRET_KEY
        generateValue: true
